# 20190116 Summary

## 1. OOP

* pass:할 말 없으니까 넘어가, 아무일도 안 일어남, 비워두면 비어져 있다고 에러 나오니까 일단 적어 두는 것
* 인스턴스 생성시 공간은 할당되지만 아무 것도 없다. `.val`으로 선언이 되야 자신을 갖는다.

```python
# Person을 만들어봅시다.
class Person:
    name = 'ssafy kim'
    def greeting(self):
        return f'hi {self.name}'
        
p=Person()#가르킬 공간만 가짐

print(p.name)
p.name = 'kim ssafy'#공간에 자신만의 것을 가짐
print(p.greeting())
#p.greeting() == Person.greeting(p)  동치
```

* self가 없으면 자기 이름인줄 모르고 나가서 찾는다. 없으면 에러나온다.

* `__init__`생성자/`__del__`소멸자- 생성 될때 , 소멸할때 호출 되는 메서드, 

```python
class Person:
    def __init__(self):
        print('응애!')
    def __del__(self):
        print('빠잉!')
        
p = Person #Person 클래스를 가르킨다. 
p2 = Person()
p3 = p() #Person()과 같다
```

* 동일 변수명으로 다른 걸 선언하면 연결이 끊어지도 없는 파일이라고 생각하고 소멸자가 돌아간다. 안에 있지만, 어차피 가르킬 수 없으니 없다고 보는 것, 소유권 행사자가 없다. 가비지 즉각 소멸

```python
class Person:
    population = 0
    def __init__(self, name):
        self.name = name
        Person.population += 1 #클래스 객체에 들어가려면 Person으로 들어가야 한다.
        
p1 = Person('john')
p2 = Person('tak')
```

클래스객체에 들어가서 변경하려면 Person으로 들어가야 한다. 이부분 유의합시다. 

잘못해서 인스턴스에서 변경하면 해당 인스턴스에 새로운 변수가 할당 될 뿐입니다.

다만 list같은 가르키는 것이라면 인스턴스 생성시에 그 위치를 받기 때문에 바꾸면 전부 바꾼다.

```python
class Person:
    population = [0]
    def __init__(self, name):
        self.name = name
        Person.population[0] += 1
kang = Person('강진우')
print(kang.name)
baek = Person('백지원')
print(baek.name)
print(Person.population[0])
kang.population[0] = 1 #Person의 객체도 바뀐다.왜? 리스트라서 가리키고 있는거, 같은 곳 가르킨다.
print(kang.population[0])
print(Person.population[0])
```

```python
class Person:
    population = 0
    def __init__(self, name):
        self.name = name
        Person.population += 1
kang = Person('강진우')
print(kang.name)
baek = Person('백지원')
print(baek.name)
print(Person.population)
kang.population = 1 #Person의 객체는 안 바뀐다. 인티저값은 스스로 값을 가지고 있다. 인스턴스내에 population 객체가 생긴다.
print(kang.population)
print(Person.population)
```

* 정적 메소드, 클래스 메소드
  * 인스턴스메소드는 강제로 자신이 들어간다. 기본적으로 인스턴스가 들어간다.
  * 클래스메소드는 강제로 클래스가 들어간다. 클래스에 접근 가능
  * 스태틱은 둘다 안받기 때문에 둘 다 접근 안하려고 할때 쓴다.

```python
# 개의 숫자를 출력하는 classmethod를 만들어보겠습니다.
class Dog:
    num_of_dogs = 0
    birth_of_dogs = 0
    list_of_dogs = [] #이렇게 선언하면 밖에서 들어 올 수 있다.
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed
        Dog.num_of_dogs += 1
        Dog.birth_of_dogs +=1
        Dog.list_of_dogs.append(name)
    def __del__(self):
        Dog.num_of_dogs -= 1
    def bark(self):
        return '왈왈!'
    @staticmethod# 스태틱으로 쓸 것을 선언 해준다. 보통은 클래스에 접근 안하는걸 쓴다.
    def info():
        return '이것은 개입니다.'
    @classmethod#정식으로 class인자를 넘겨 줘서 일 할때 사용한다.
    def birth(cls): # 꼭cls일 필요는 없다. 
        return f'Birth: {cls.birth_of_dogs}, Current: {cls.num_of_dogs}'
d1 = Dog('초코', '푸들')
d2 = Dog('꽁이', '말티즈')
d3 = Dog('별이', '시츄')
print(Dog.info())
print(Dog.birth())
l = Dog.list_of_dogs #이런 식으로 내부 인자의 주소를 받아서 바꿀 수 있다. 보안이 필요하다
l.append('cat')
```

```markdown
각 연산을 정의 할 수 있다.
+  __add__   
-  __sub__
*  __mul__
<  __lt__
<= __le__
== __eq__
!= __ne__
>= __ge__
>  __gt__
```

```python
class Stack:
    def __init__(self):
        self.items = []
    def empty(self):
        return True if self.items == [] else False
    def top(self):
        return None if self.empty() else self.items[-1]
    def pop(self):
        if self.empty() :
            return None
        else :
            self.a = self.items[-1]
            self.items = self.items[0:-1]
            return self.a
    def push(self, item):
        self.items += [item]
    def __repr__(self): #해당 객체를 자체가 리턴하는 값
        return '\n'.join(self.items)
    def __str__(self): #해당 객체를 print했을때 리턴하는 값
        return 'ㅣ'.join(self.items)
```

* 상속

```python
class Person:
    population = 0
    def __init__(self, name = '사람'):
        self.name = name
        Person.population += 1
        
    def greeting(self):
        print(f'반갑습니다, {self.name}입니다.')

class Student(Person):
    def __init__(self, student_id, name='학생'):#overwriting
        self.name = name
        self.student_id = student_id
        Person.population += 1
        
s=Student(1)
issubclass(Person, Student)#False, 앞에가 뒤의 서브 클래스냐? 반대다
issubclass(Student, Person)#True
isinstance(s,Student)#True
isinstance(s,Person)#True 상속 받은 것도 해당으로 본다.
```

* `super()`:자식 클래스에 메서드 추가 구현 할때 부모 내용 사용하고자 할때 사용

```python
class Person:
    def __init__(self, name, age, number, email):
        self.name = name
        self.age = age
        self.number = number
        self.email = email 
        
    def greeting(self):
        print(f'안녕, {self.name}')
        
class Student(Person):
    def __init__(self, name, age, number, email, student_id):
        #Person그대로 받는다.
        super().__init__(name, age, number, email)#상속 준쪽에 요구하는걸 넣어줘야 한다.
        self.student_id = student_id
```

* 다중 상속: 여러개에서 상속 받는다.
  * 겹치는게 있다면 앞쪽에 넣어 준 것을 받는다.

```python
class Person:
    def __init__(self, name):
        self.name = name
    def breath(self):
        return '날숨'    
    def greeting(self):
        return 'hi' + self.name
class Mom(Person):
    gene = 'XX'
    def swim(self):
        return '첨벙첨벙'
class Dad(Person):
    gene = 'XY'
    def kick(self):
        return '슛'
class Child(Dad, Mom):
    def cry(self):
        return '응애'
c = Child('애')
c.swim()
c.kick()
c.gene #XY다.순서상 왼쪽에서 오른쪽으로 overwrighting
c.cry()
```

## 2. 모듈

* 코드 덩어리, `random`, `math` 등 `dir(random)`으로 어떤 메소드가 있는지 보자
* 여러가지 써 볼것

## 3. Error , 예외처리

* 모든 에러는 클래스, 상속 받고 있다.

```python
try:#블럭에서 한다.
    num = input('0이 아닌 정수를 입력해: ')
    100 / int(num)
except ValueError:
    print('정수라고')
except ZeroDivisionError:
    print('0말고')
except:#정하지 않은 에러는 전부 이쪽
    print('...?')
```

```python
try:
    num = input('0이 아닌 정수를 입력해: ')
    100 / int(num)
except Exception:#이런식으로 앞에 놓이면 어떤 에러든 여기로 빨려 들어간다.
    print('...?')
except ValueError:
    print('정수라고')
except ZeroDivisionError:
    print('0말고')
```

```python
# 에러 메세지를 넘겨줄 수도 있습니다.
try:
    a = []
    print(a[0])
except IndexError as errmsg:
    print(f'{errmsg} 오류입니다. 아마 범위 밖의 index를 넣으셨나봐요 ^오^')
```

* `finally`는 에러가 있든 없든 무조건 실행해야 하는 것을 넣는다.
* `raise ValueError`이 방법으로 에러를 직접 낼 수 있다.

```python
def my_div(num1, num2):
    try:
        return num1 / num2
    except ZeroDivisionError:
        print('division by zero 오류가 발생하였습니다.')
    except TypeError:
        raise ValueError('숫자를 넣어주세요')
```

* `assert` 는 조건부로 에러를 발생 시킨다.

```python
def my_div(x, y):#assert 뒤의 주장이 맞으면 다음줄 아니면 해당에 넣어준 에러 메시지
    assert type(x) == int and isinstance(y, int), '문자를 입력했네요'
    assert y, '0으로 못나눠요'
    print('나눗셈을 시작합니다.')
    try:
        result = x / y
    except ZeroDivisoinError as e:
        print(f'{e} 에러 발생!')
    else:
        return result
```











































